### PR TITLE
Main.css: Fix broken social link Fixes https://github.com/coala/gci-leaders/issues/73

### LINKED ISSUE #73: Broken social link
broken2
broken1

This probably comes from trying to place a chat link, even though Catrobat doesn't have one.

### PR DESCRIPTION
**Pull request by mvinoba**
Fixes #73 using @wisn [suggestion](https://github.com/coala/gci-leaders/issues/73#issuecomment-356026381).

### CODE REVIEW

**Review by wisn — APPROVED** [review]

**Review by newbazz — CHANGES_REQUESTED** [review]
This doesnt follow commit guidelines

**Comment by mvinoba** [comment]
@newbazz What would be the appropriate changes to the commit? This is my first PR, I apologise any mistake on common guidelines.

**Comment by blazeu** [comment]
You forgot to put `Fixes https://github.com/coala/gci-leaders/issues/73` on your commit body

**Review by newbazz — CHANGES_REQUESTED** [review]
Appropriate commit msg might be 
`Main.css: Fix broken social link
Fixes <issue_link`

**Comment by mvinoba** [comment]
@newbazz Not sure if it's done right now or if it should be just #73 to reference the issue on commit message.

**Review by newbazz — COMMENTED** [review]
nope it is still not correct, btw it was my fault though, commit message sud be 
`Main.css: Fix broken social link`
`Fixes https://github.com/coala/gci-leaders/issues/73` this is how it sud be

**Comment by newbazz** [comment]
in two different line

**Comment by mvinoba** [comment]
@newbazz Thanks! Please check if it's correct now, apparently I mistook the PR title with the commit message.

**Comment by blazeu** [comment]
coala says:
```
|    | [NORMAL] GitCommitBear:
|    | No newline found between shortlog and body at HEAD commit. Please add one.
```
Your commit needs to be like this
```
Main.css: Fix broken social link

Fixes https://github.com/coala/gci-leaders/issues/73
```

1 newline between shortlog and body.

**Comment by mvinoba** [comment]
@newbazz It should be ok now, GitCommitBear ran without warnings.

**Review by newbazz — COMMENTED** [review]
This is how the issue was to be solved?

**Comment by mvinoba** [comment]
I implemented wisn's [suggestion](https://github.com/coala/gci-leaders/issues/73#issuecomment-356026381), the one that made the issue a newcomer one, but perhaps there are better ways to solve this issue.

**Review by newbazz — APPROVED** [review]
LGTM

**Comment by blazeu** [comment]
ack https://github.com/coala/gci-leaders/pull/142/commits/5fe816cf49d2f6d4360c86c86b4402e0b5fede63

**Review by blazeu — APPROVED** [review]

**Comment by blazeu** [comment]
@gitmate-bot ff

**Pull request merged**
