### PR TITLE
Show that GCI has ended

### PR DESCRIPTION
**Pull request by blazeu**

### CODE REVIEW

**Comment by blazeu** [comment]
The build might fail after the GCI has really ended/full announced (1 Feb?) 

So this might be the last chance to edit it without tweaking the build.

**Comment by jayvdb** [comment]
Shouldnt this be 'Fixes https://github.com/coala/gci-leaders/issues/138' ?

**Comment by blazeu** [comment]
Aha, didn't even realize there was an issue.

**Review by jayvdb — APPROVED** [review]

**Comment by jayvdb** [comment]
ack https://github.com/coala/gci-leaders/pull/140/commits/0aa42a713a75e5338efd52dcb6bfb0eb5a3fc456

**Comment by jayvdb** [comment]
@gitmate-bot rebase

**Comment by jayvdb** [comment]
@gitmate-bot ff

**Pull request merged**
