### PR TITLE
main.html: edit image path

### PR DESCRIPTION
**Pull request by danes44**
This edit the path to the GCI logo

Fixes https://github.com/coala/gci-leaders/issues/88

### CODE REVIEW

**Review by blazeu — CHANGES_REQUESTED** [review]
Still 404.

Also, even though it's the correct url, the image will not display correctly in Facebook, because it's too small.

The issue said to replace it with bigger one (add a new image). Please read it again.

**Comment by blazeu** [comment]
Add new image with enlarged logo.

**Comment by danes44** [comment]
I have add a new image with enlarged logo, but I have no idea why it doesn't work

**Comment by blazeu** [comment]
The logo is not committed. See https://github.com/coala/gci-leaders/pull/128/files

`git add -A` before `git commit` ?

**Comment by danes44** [comment]
Yes, I was write `git add -A` before `git commit`. Is it wrong?

**Comment by danes44** [comment]
done @blazeu

**Comment by blazeu** [comment]
Wow it's too big ... and not centered. We want it to have padding but still centered.

I think we want "small images" mentioned in https://developers.facebook.com/docs/sharing/best-practices

400x400 sounds ok ish .. or try to keep the 1.91:1 aspect ratio as mentioned in that docs.

Also need to rebase. ask this in the chat if you can't.

**Comment by danes44** [comment]
oh okay i'll fix it

**Comment by danes44** [comment]
@blazeu done

**Comment by blazeu** [comment]
Need that padding (empty space) around the logo, don't remove it.

**Comment by danes44** [comment]
done @blazeu

**Comment by blazeu** [comment]
Cool, but your commit message needs a rewrite, run `git commit --amend` again.

Should be `Add new image for og:image` , note the capital on the first letter.

**Comment by danes44** [comment]
done @blazeu 
just changes the commit body right?

**Comment by blazeu** [comment]
No, change this `main.html: edit image path`

Keep the commit body to `Fixes ..` only

**Comment by danes44** [comment]
oh, done. @blazeu

**Review by blazeu — APPROVED** [review]

**Comment by blazeu** [comment]
ack 
https://github.com/coala/gci-leaders/pull/128/commits/447fd44bc5e35f8068efce7e63f5784b50819d5a

**Comment by blazeu** [comment]
@danes44 Please don't remove the newline between commit shortlog and body

image
Commit on the bottom is correct, yours is wrong.

```
[SHORTLOG]

[BODY]

[Fixes ..]
```

**Pull request merged**
