### PR TITLE
Update deadline

### PR DESCRIPTION
**Pull request by daniellimws**
Currently the progress is exceeding 100% as it is looking at the wrong deadline.

Update the deadline used to report the actual time left.

### CODE REVIEW

**Review by mkljczk — APPROVED** [review]

**Comment by blazeu** [comment]
This will be negative numbers again when the competition really ends. Not really a "fix".
Editing the locale file is also not good, since you have to update all of the language.

I think we have a `timeDifference` function for handling past time. 
Go edit this instead https://github.com/coala/gci-leaders/blob/master/src/js/app.js#L36

Yeah, having 2 separate function for generating relative time is _stupid_, I know.
I'd be really happy if you refactor that into a single function, but not mandatory.

**Comment by daniellimws** [comment]
Sure, I'll work on that tomorrow, though may be a bit lazy because 2 weeks later this website will be kinda obsolete.

**Comment by jayvdb** [comment]
unack https://github.com/coala/gci-leaders/pull/139/commits/2823ef61aaa67a94650f4798b495e290c1088e13

**Comment by Makman2** [comment]
Please don't close PRs just because they weren't acked, you can always audit a PR.

**Pull request closed without merging**
