### PR TITLE
added hover effects

### PR DESCRIPTION
**Pull request by Ananthavijay**
added hover effects as in GCI website.

check this :

ec349368772e4159acb06b0439d6253a

### CODE REVIEW

**Comment by Ananthavijay** [comment]
why the Travis build is failing?

**Comment by jayvdb** [comment]
Do not close PRs.

**Comment by jayvdb** [comment]
Do we have an issue about this?

If not, could you please create one.

We will get the CI fixed soon.

**Comment by Ananthavijay** [comment]
No probs @jayvdb

**Comment by jayvdb** [comment]
@Ananthavijay the build is fixed ;-)

rebase and we'll be able to see your changes on netlify

**Comment by Ananthavijay** [comment]
k

**Comment by jayvdb** [comment]
Am I right that this is solving https://github.com/coala/gci-leaders/issues/158 ?

Could you rebase, and ideally also update your commit message to follow https://coala.io/commit

**Comment by Ananthavijay** [comment]
yep @jayvdb I will make it after gci ends

**Comment by Ananthavijay** [comment]
Rebased and updated the commit message @jayvdb I guess the Travis isn't fixed
I think its because the API limit reached

**Pull request closed without merging**
