### PR TITLE
Re-add GCI logo for the Open Graph protocol

### LINKED ISSUE #88: og:image is broken
https://github.com/coala/gci-leaders/blob/206a75c24f14f10f744a574c87920d6d07dfe218/templates/main.html#L9

https://gci-leaders.netlify.com/images/GCI-logo.jpg = 404

Also, consider replacing it with slightly bigger one + padding on the sides for better look on share card such as Facebook.

>**Minimum Image Size**
>The minimum image size is 200 x 200 pixels. If you try to use an image smaller than this you will see an error in the Sharing Debugger.
>https://developers.facebook.com/docs/sharing/best-practices/

### PR DESCRIPTION
**Pull request by zwliew**
The image was previously moved in commit 80d577d4c52197c590afa303fbd6ef4a82611392, causing the image URL to return a 404 error.
Re-add the original image to fix OGP support.

Fixes #88

### CODE REVIEW

**Comment by andrewda** [comment]
Why are you adding a new image and not using https://github.com/coala/gci-leaders/blob/master/static/images/logos/gci.png?

**Comment by zwliew** [comment]
According to the [Best Practices doc](https://developers.facebook.com/docs/sharing/best-practices) mentioned in the original issue, the image size has to be at least 200x200 pixels for smaller sharing posts, or 600x315 pixels for larger sharing posts.

The current image is 72x72 pixels (after commit [f95ffaf214f529b69de444760653ce75f2621410](https://github.com/coala/gci-leaders/commit/f95ffaf214f529b69de444760653ce75f2621410), so I decided to re-add the previous image instead.

**Comment by andrewda** [comment]
Alright, sounds good. Is a transparent or non-transparent image preferred?

**Comment by zwliew** [comment]
I believe an image with a white background works and looks fine.

Example using an image with a white background:
capture

**Review by blazeu — CHANGES_REQUESTED** [review]
>padding on the sides for better look on share card such as Facebook.

**Comment by blazeu** [comment]
Actually we prefer small thumbnail because it's just a logo.

**Comment by blazeu** [comment]
Hey @zwliew do you still want to work on this?

If not then I will close the PR so that another student can work on it.

Don't worry, you don't need to rush if you're still busy with the other org.

**Comment by zwliew** [comment]
Sorry, I'll close this so others can work on it.

**Pull request closed without merging**
