### PR TITLE
Changed Haiku's wikidata url

### LINKED ISSUE #123: Fix Haiku's wikidata link
Currently being found to be: https://www.wikidata.org/wiki/Q37707
Should be: https://www.wikidata.org/wiki/Q215448

### PR DESCRIPTION
**Pull request by apoorvaagupta**
Signed-off-by: Apoorvaa Gupta <apoorvaagupta01@gmail.com>

Fixes #123

### CODE REVIEW

**Comment by apoorvaagupta** [comment]
Hello @Makman2 
I have just replaced the wrong wikidata url with the correct one in the data.min.json file on gh-pages branch. But this is showing some error in deploying thought I haven't changes any other file.
Please help!!

**Review by newbazz — CHANGES_REQUESTED** [review]
you have not followed the commit guidelines.

**Comment by apoorvaagupta** [comment]
Hello, @newbazz Can you please tell me my mistake?!
I am new to coala!

**Comment by ishanSrt** [comment]
@apoorvaagupta did you go through the newcomer's guide?
anyways here are the commit guidelines: https://api.coala.io/en/latest/Developers/Writing_Good_Commits.html

**Comment by ishanSrt** [comment]
Seriously what are the changes that you made?
screen shot 2018-02-04 at 2 30 35 am

**Comment by ishanSrt** [comment]
Does gitmate not check for the proper phrasing of commit messages? @newbazz what I mean is division of shortlog and/or body and last line

**Comment by jayvdb** [comment]
Changing the data file is not the correct solution.

**Pull request closed without merging**
