### PR TITLE
generate.js: Make org name clickable to GCI organization page

### PR DESCRIPTION
**Pull request by tioirawan**
Fixes https://github.com/coala/gci-leaders/issues/3

### CODE REVIEW

**Comment by blazeu** [comment]
The shortlog needs to be 50 characters or less.
http://api.coala.io/en/latest/Developers/Writing_Good_Commits.html#shortlog

**Comment by blazeu** [comment]
unack https://github.com/coala/gci-leaders/commit/e70bf2120048a36ac066a26fa706e6e57ce77bd5

**Comment by tioirawan** [comment]
My shortlog is just 48 characters long

**Comment by blazeu** [comment]
No, the tag is included as well, thus your shortlog is 61 characters 😉

**Comment by tioirawan** [comment]
fixed

**Comment by blazeu** [comment]
You need to explain that "it links to the corresponding GCI organization page" in your commit body.

**Comment by tioirawan** [comment]
Done

**Review by blazeu — APPROVED** [review]

**Comment by blazeu** [comment]
ack https://github.com/coala/gci-leaders/pull/13/commits/4a4924d29f81c220c1fed5640b4e685282b12fd1

**Pull request merged**
